var Metinler = {
  tr: {
    VarsayilanKulAd: "Kullanıcı",
    UygDil: "Uygulama Dili",
    KelimeDil: "Kelime Dili",
    KullAd: "Kullanıcı Adı",
    "Hece Rengi": "Hece Rengi",
    Kaydet: "Kaydet",
    Türkçe: "Türkçe",
    İngilizce: "İngilizce",
    keldk: "kel./dk.",
    Az: "Az",
    Normal: "Normal",
    Cok: "Çok",
    Hiz: "Hız",
    HarfSayisi: "Harf Sayısı",
    "Kayan Yazı": "Kayan Yazı",
  },
  en: {
    Ayarlar: "Settings",
    VarsayilanKulAd: "User",
    UygDil: "App. Language",
    KullAd: "User Name",
    "Hece Rengi": "Syllable Color",
    Kaydet: "Save",
    Türkçe: "Turkish",
    İngilizce: "English",
    keldk: "word/min.",
    Az: "Min",
    Normal: "Medium",
    Cok: "Max",
    Hiz: "Speed",
    HarfSayisi: "Num. of Letters",
    KelimeDil: "Word Lang.",
    "Kayan Yazı": "Sliding Text",
    "Okuma Hızı": "Reading Speed",
    Kelime: "Word",
    "Sonu Farklı": "Diff. Last Letter",
    "İlki Farklı": "Diff. First Letter",
    "Ekli Kelime": "Attached Word",
    "Karışan Harfler": "Confusing Letters",
    Hafıza: "Memory",
    Heceler: "Syllable",
    DEVAM: "Cont.",
    "Kelime Tür": "Word Type",
    BAŞLA: "START",
    "Başla Tuşuna Bas": "Press Start",
  },
};

export default Metinler;
